#include <iostream>

using namespace std;

int main()
{

    /**
    WHILE: LA CONDICION SE EVALUA ANTES DE ENTRAR AL BLOQUE
    DE CODIGO. SI LA CONDICION ES FALSA DESDE EL PRINCIPIO,
    EL CODIGO DENTRO DEL WHILE NO SE EJECUTA NUNCA (0 VECES).

    DO-WHILE: EL BLOQUE DE CODIGO SE EJECUTA PRIMERO Y LA
    CONDICION SE EVALUA DESPUES. ESTO GARANTIZA QUE EL
    CODIGO SE EJECUTE AL MENOS UNA VEZ, SIN IMPORTAR SI LA
    CONDICION ES VERDADERA O FALSA AL INICIO.

    /**
    UN SISTEMA DE SEGURIDAD DE UNA PLATAFORMA DIGITAL
    REQUIERE VALIDAR LA EDAD DE LOS USUARIOS ANTES
    DE PERMITIR EL REGISTRO.
    SOLO PUEDEN ACCEDER PERSONAS QUE TENGAN 13 AÑOS O MAS.
    */

    int edad;

    do
    {
        cout << "Ingrese edad: ";
        cin >> edad;
    }
    while(edad < 13); /// MIENTRAS LA EDAD SEA MENOR A 13 SE REPITE EL CICLO


    return 0;
}

